db:
  max_connections: 1
logger:
  path: log/test.log
  level: <%= Logger::FATAL %>
rabbitmq:
  host: <%= ENV.fetch('RABBITMQ_HOST') %>
  username: <%= ENV.fetch('RABBITMQ_USER') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD') %>
